#!/bin/bash
current_dir=`pwd -P` # -L for symlink
while [ "$current_dir" != "/" ]
do
    if [ -f "$current_dir/mvnw" ]
    then
        break;
    fi
    current_dir=`dirname "$current_dir"`
done

if [ "$current_dir" != "/" ]
then
    bash "$current_dir/mvnw" "$@"
else
    echo "No mvnw file exists."
fi
